using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEngine;
using UnityEngine.XR.ARSubsystems;

namespace Unity.XR.XREAL.Samples
{
    /// <summary>
    /// This class provides functionality to save meshes generated by AR systems,
    /// including classified meshes, into organized directories. It also supports
    /// converting meshes to and from OBJ format strings.
    /// </summary>
    public static class MeshSaveUtility
    {
        static int m_SubFolderIndex = 0;

        static string SavePath
        {
            get
            {
                string folder;
#if UNITY_EDITOR
                folder = Directory.GetCurrentDirectory();
#else
                folder = Application.persistentDataPath;
#endif
                return Path.Combine(folder, "MeshSave");
            }
        }

        static MeshSaveUtility()
        {
            DirectoryInfo directoryInfo = new DirectoryInfo(SavePath);
            if (!directoryInfo.Exists)
            {
                directoryInfo.Create();
            }
            else
            {
                while (m_SubFolderIndex < int.MaxValue)
                {
                    string subFolder = Path.Combine(SavePath, m_SubFolderIndex.ToString());
                    directoryInfo = new DirectoryInfo(subFolder);
                    if (directoryInfo.Exists)
                        m_SubFolderIndex++;
                    else
                        break;
                }
            }

        }

        /// <summary>
        /// Saves a dictionary of meshes to OBJ files in a new subfolder.
        /// Each mesh is saved as a separate OBJ file, named by its key in the dictionary.
        /// </summary>
        /// <param name="meshDictCopy">A dictionary containing meshes to save, keyed by their unique IDs.</param>
        public static void Save(Dictionary<ulong, Mesh> meshDictCopy)
        {
            DirectoryInfo directoryInfo = new DirectoryInfo(Path.Combine(SavePath, m_SubFolderIndex.ToString()));
            if (!directoryInfo.Exists)
            {
                directoryInfo.Create();
            }
            foreach (var item in meshDictCopy)
            {
                FileInfo fileInfo = new FileInfo(Path.Combine(directoryInfo.FullName, item.Key.ToString() + ".obj"));
                StreamWriter sw = new StreamWriter(fileInfo.FullName);
                string str = MeshToString(item.Value);
                sw.Write(str);
                sw.Flush();
                sw.Close();
                Debug.Log($"[MeshSaveUtility] Save to {fileInfo.FullName}");
            }

            m_SubFolderIndex++;
        }

        /// <summary>
        /// Saves classified meshes to OBJ files in a new subfolder.
        /// Meshes are organized by their TrackableId and semantic label.
        /// </summary>
        /// <param name="meshDict">A dictionary containing classified meshes, keyed by TrackableId and semantic label.</param>
        public static void SaveFrackingMesh(Dictionary<TrackableId, Dictionary<NRMeshingVertexSemanticLabel, MeshFilter>> meshDict)
        {
            DirectoryInfo directoryInfo = new DirectoryInfo(Path.Combine(SavePath, m_SubFolderIndex.ToString()));
            if (!directoryInfo.Exists)
            {
                directoryInfo.Create();
            }

            foreach (var kv in meshDict)
            {
                var id = kv.Key;
                var labelMeshDict = kv.Value;
                foreach (var item in labelMeshDict)
                {
                    FileInfo fileInfo = new FileInfo(Path.Combine(directoryInfo.FullName, $"{id.subId2}_{item.Key}.obj"));
                    StreamWriter sw = new StreamWriter(fileInfo.FullName);
                    string str = MeshToString(item.Value.mesh);
                    sw.Write(str);
                    sw.Flush();
                    sw.Close();
                    Debug.Log($"[MeshSaveUtility] Save to {fileInfo.FullName}");
                }
            }
            m_SubFolderIndex++;
        }

        /// <summary>
        /// Clears all saved OBJ files in the base save directory.
        /// </summary>
        public static void Clear()
        {
            DirectoryInfo directoryInfo = new DirectoryInfo(SavePath);
            if (directoryInfo.Exists)
            {
                foreach (var file in directoryInfo.EnumerateFiles("*.obj"))
                {
                    file.Delete();
                }
            }
        }

        /// <summary>
        /// Converts a Mesh object to an OBJ format string.
        /// </summary>
        /// <param name="mesh">The mesh to convert.</param>
        /// <returns>A string representing the mesh in OBJ format.</returns>
        public static string MeshToString(Mesh mesh)
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("# \n");

            Vector3[] vertices = mesh.vertices;
            foreach (Vector3 v in vertices)
            {
                sb.Append(string.Format("v {0} {1} {2}\n", v.x, v.y, v.z));
            }
            sb.Append("\n");

            Vector3[] normals = mesh.normals;
            foreach (Vector3 vn in normals)
            {
                sb.Append(string.Format("vn {0} {1} {2}\n", vn.x, vn.y, vn.z));
            }
            sb.Append("\n");

            int[] triangles = mesh.triangles;
            for (int i = 0; i < triangles.Length; i += 3)
            {
                sb.Append(string.Format("f {0}/{0}/{0} {1}/{1}/{1} {2}/{2}/{2}\n",
                    triangles[i] + 1, triangles[i + 1] + 1, triangles[i + 2] + 1));
            }
            sb.Append("\n");
            return sb.ToString();
        }

        /// <summary>
        /// Converts an OBJ format string to a Mesh object.
        /// </summary>
        /// <param name="data">The OBJ format string to convert.</param>
        /// <returns>A Mesh object reconstructed from the OBJ data.</returns>
        public static Mesh StringToMesh(string data)
        {
            var lines = data.Split('\n');
            List<Vector3> verticeList = new List<Vector3>();
            List<Vector3> normalList = new List<Vector3>();
            List<int> triangleList = new List<int>();

            foreach (var line in lines)
            {
                var nums = line.Split(' ', '/');
                switch (nums[0])
                {
                    case "v":
                        verticeList.Add(new Vector3(float.Parse(nums[1]), float.Parse(nums[2]), float.Parse(nums[3])));
                        break;
                    case "vn":
                        normalList.Add(new Vector3(float.Parse(nums[1]), float.Parse(nums[2]), float.Parse(nums[3])));
                        break;
                    case "f":
                        triangleList.Add(int.Parse(nums[1]) - 1);
                        triangleList.Add(int.Parse(nums[4]) - 1);
                        triangleList.Add(int.Parse(nums[7]) - 1);
                        break;
                    default:
                        break;
                }
            }

            return new Mesh
            {
                vertices = verticeList.ToArray(),
                normals = normalList.ToArray(),
                triangles = triangleList.ToArray()
            };
        }
    }
}
